//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebConsumerProfile
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public Nullable<long> PhoneNo { get; set; }
        public Nullable<long> AlternativePhoneNo { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public Nullable<long> PINCode { get; set; }
        public string LongStayYear { get; set; }
        public string LongStayMonth { get; set; }
        public Nullable<int> IsPermanent { get; set; }
        public Nullable<long> AdharNo { get; set; }
        public string Occupation { get; set; }
        public string EmployementNo { get; set; }
        public string Designation { get; set; }
        public string SalaryRange { get; set; }
        public string SavetoDraff { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> Enabled { get; set; }
    }
}
