//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebConsumerDetail
    {
        public int ConsumerID { get; set; }
        public string ConsumerName { get; set; }
        public string Email { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public string Location { get; set; }
        public Nullable<int> Enabled { get; set; }
        public Nullable<System.DateTime> LastOrder { get; set; }
        public Nullable<int> DealerId { get; set; }
    }
}
