//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebDealarDetail
    {
        public int RecordId { get; set; }
        public string CountryName { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public string DelarName { get; set; }
        public Nullable<int> Enabled { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
